from flask import Flask, request, jsonify
from flask_cors import CORS
import os
import xml_parser

app = Flask(__name__)
CORS(app)

UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@app.route('/api/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
    
    if file:
        filepath = os.path.join(UPLOAD_FOLDER, file.filename)
        file.save(filepath)
        
        # Trigger processing (async in a real app, sync here for MVP)
        try:
            # We'll expect the parser to return summary stats or just acknowledge success
            stats = xml_parser.parse_and_summarize(filepath)
            return jsonify({'message': 'File processed successfully', 'stats': stats}), 200
        except Exception as e:
            return jsonify({'error': str(e)}), 500

@app.route('/api/health-metrics', methods=['GET'])
def get_metrics():
    # In a real app, we'd query a DB. Here we might read from the processed CSVs/JSONs
    # generated by the parser.
    return jsonify(xml_parser.get_latest_metrics())

if __name__ == '__main__':
    app.run(debug=True, port=5001)
